"""Utility for generating keysym to Unicode mappings.

This module fetches and parses the keysyms.txt file to generate a Python dictionary
mapping XKB keysyms to Unicode characters.
"""
import os
import re
from typing import Dict, Optional

import requests


KEYSYM_URL = 'https://www.cl.cam.ac.uk/~mgk25/ucs/keysyms.txt'
CUR_DIR = os.path.dirname(os.path.abspath(__file__))


def generate_map() -> None:
    """Fetch and parse the keysyms.txt file to generate a Python dictionary.
    
    This function downloads the keysym mapping data from a remote URL,
    parses it, and generates a Python module with a comprehensive mapping
    from XKB keysyms to Unicode characters.
    
    The generated file is saved as 'mapping_generated.py' in the current directory.
    """
    try:
        response = requests.get(KEYSYM_URL, verify=False)
        response.raise_for_status()
        content = response.text
    except requests.exceptions.RequestException as e:
        print(f'Error fetching keysym file: {e}')
        return

    keysym_map: Dict[str, str] = {}
    # Regex to find lines with a Unicode mapping and a keysym name.
    # Captures Unicode hex (e.g., '00C1') and keysym name (e.g., 'Aacute').
    pattern = re.compile(r'U([0-9A-F]{4,6})\s+.*\s+#\s*(\S+)')

    for line in content.splitlines():
        match = pattern.search(line)
        if match:
            unicode_hex = match.group(1)
            keysym_name = match.group(2)
            # Convert hex to integer, then to character.
            # We escape backslashes and single quotes for the final Python string.
            unicode_val = chr(int(unicode_hex, 16))
            # Replace null byte with an empty string to avoid syntax errors
            if unicode_val == '\x00':
                unicode_char = ''
            else:
                unicode_char = unicode_val.replace('\\', '\\\\').replace("'", "\\'")

            # We ignore deprecated aliases and take the first one.
            if keysym_name not in keysym_map:
                keysym_map[keysym_name] = unicode_char

# FIXME we add missing keysyms manually for now;

    EXTRA = {
        'exclamdown': '¡',
        'EuroSign': '€', 
        'sterling': '£',
        'cent': '¢',
        'infinity': '∞',
        'section': '§',
        'paragraph': '¶',
        'degree': '°',
        'ordfeminine': 'ª',
        'periodcentered': '·',
        'masculine': 'º',
        'singlelowquotemark': '‚',
        'plusminus': '±',
        'doublelowquotemark': '„',
        'acute': '´',
        'registered': '®',
        'permille': '‰',
        'yen': '¥',
        'onequarter': '¼',
        'diaeresis': '¨',
        'oslash': 'ø',
        'Oslash': 'Ø',
        'Greek_pi': 'π',
        'leftdoublequotemark': '"',
        'rightdoublequotemark': '"',
        'aring': 'å',
        'Aring': 'Å',
        'ssharp': 'ß',
        'eth': 'ð',
        'copyright': '©',
        'onehalf': '½',
        'notsign': '¬',
        'THORN': 'Þ',
        'thorn': 'þ',
        'ae': 'æ',
        'AE': 'Æ',
        'Greek_OMEGA': 'Ω',
        'ccedilla': 'ç',
        'Ccedilla': 'Ç',
        'squareroot': '√',
        'integral': '∫',
        'mu': 'μ',
        'threequarters': '¾',
        'division': '÷',
        'questiondown': '¿',
    }
    keysym_map.update(EXTRA)


    # Generate the Python dictionary code
    output = '"""Auto-generated by generate_keysym_map.py.\n\n'
    output += 'This module contains a comprehensive mapping from XKB keysyms to Unicode characters.\n'
    output += '"""\n\n'
    output += 'from typing import Dict, Optional\n\n\n'
    output += 'KEYSYM_MAP: Dict[str, str] = {\n'
    for name, char in sorted(keysym_map.items()):
        output += f"    '{name}': '{char}',\n"
    output += '}\n\n\n'
    output += 'def keysym_to_unicode(keysym: str) -> str:\n'
    output += '    """Convert an XKB keysym to a Unicode character.\n\n'
    output += '    Args:\n'
    output += '        keysym: The XKB keysym to convert.\n\n'
    output += '    Returns:\n'
    output += '        The Unicode character corresponding to the keysym, or an empty string if not found.\n'
    output += '    """\n'
    output += '    return KEYSYM_MAP.get(keysym, keysym if len(keysym) == 1 else "")\n'

    with open(f'{CUR_DIR}/mapping_generated.py', 'w', encoding='utf-8') as f:
        f.write(output)

    print('Successfully generated mapping_generated.py')

if __name__ == '__main__':
    generate_map()
